name: Set Environment Vars

on: 
  push:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
  XCODEV: '13.4.1'
  RELEASEV: '4.1.10'
  
jobs:
  set-env-vars:
    runs-on: [macos-latest]
    env:
      XCODEV: '13.4.1'
      RELEASEV: '4.1.10'
    steps:
      - name: Set environment variables
        run: echo "XCODEV=${env.XCODEV}" >> $GITHUB_ENV
